[package]
name = "memristor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["svg"] }
thiserror = "2.0.17"
tempdir = "0.3.7"
rfd = "0.17.1"
miniserde = "0.1.45"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
